### PR TITLE
Shorten method codes

### LINKED ISSUE #1: "We can't place the order" at PayPal Review Step
We've had a report of this error on PayPal review step when clicking place order. 

It's been identified as related to https://github.com/magento/magento2/issues/5021

It appears that checkout doesn't complete if the carrier and method code are too long when concatenated.  We see this because the code is truncated:

```
Royal Mail Method: meanbee_royalmail_secondclasssmallparcel {"is_exception":false} []
Royal Mail Method: meanbee_royalmail_firstclasssignedforsma {"is_exception":false} []
```

### PR DESCRIPTION
**Pull request by bobbyshaw**
Shorten method codes to avoid core Magento issues. Fixes #1 .

### CODE REVIEW

**Review by punkstar — COMMENTED** [review]
Do you know why the tests are now checking `carriers/rm/active` instead of `carriers/meanbee_royalmail/active` for the active check?

https://travis-ci.org/meanbee/magento2-royalmail/jobs/234797256

**Review by punkstar — COMMENTED** [review]
Can we add one unit test in here that loops through every single shipping method that is generated and ensures that the code is less than 10 characters? That'll help us catch potential problem methods in the future that accidentally go over the 10 char limit.

**Comment by bobbyshaw** [comment]
I merged in a separate PR that must have broke those carrier code tests. I ignored travis comments because it seems to be unable to find the the phpunit class in php 7 and haven't debugged a resolution yet. 

Do you know that it's a 10 character limit? I've just reduced all the code lengths that I can on a whim because it seems to make it work but I haven't been able to validate the required length.

**Comment by bobbyshaw** [comment]
@punkstar Any recommendations on how to test when currently I mock the royal mail library in all tests? Should I have a separate instance that doesn’t mock? Technically the shortening is in the new method class which I've imported into the module but this doesn't have any knowledge of what's coming in.

**Comment by bobbyshaw** [comment]
New test submitted.

**Review by punkstar — APPROVED** [review]

**Pull request merged**
